title:
  image: images/coolsoftware-blog.png

contact_links:
-
  github: https://github.com/coolsoftware/
-
  mailto: vitalyyakovlev777@gmail.com

favorite_posts:
- 
  name: Полезные ссылки
  url: tags/полезные-ссылки/
- 
  name: Howto
  url: tags/howto/
- 
  name: Музыка
  url: 2021/01/blog-post/
- 
  name: Поиск подстрок с помощью дерева цифрового поиска
  url: tags/trie/
- 
  name: Дерево Интервалов (Отрезков)
  url: tags/дерево-интервалов/
- 
  name: Throttling
  url: tags/throttling/
-
  name: В одну строку
  url: 2022/01/nodejs/

menu:
  Архив: archives
  Search:
    icon: "\uf002"
    link: search
  RSS: 
    icon: "\uf09e"
    link: atom.xml
    target: _blank

widgets:
- contactlinks
- favoriteposts
- category
- tagcloud

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: gitalk

# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
